title: Electronics Self-Learn
description: A self-learning platform for electronics fundamentals
theme: minima

minima:
  skin: classic
  include_css:
    - /assets/css/custom.css

    
# Add this line:
include:
  - _includes/head-custom.html

