title: Electronics Self-Learn
description: A self-learning platform for electronics fundamentals
theme: minima

minima:
  skin: classic
  include_css:
    - /assets/css/custom.css


markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
